const mongoose = require("mongoose");
const Country = require("../models/country");
require("dotenv").config();

const countries = [
  {
    code: "IN",
    name: "India",
    nativeName: "भारत",
    flag: "🇮🇳",
    dialCode: "+91",
    currency: { code: "INR", symbol: "₹", name: "Indian Rupee" },
    exchangeRate: 1,
    domain: "amazon.in",
    language: "en",
    timezone: "Asia/Kolkata",
    tax: { type: "GST", rate: 18, label: "GST", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 499,
      standardCost: 49,
      expressCost: 99,
      estimatedDays: { standard: 5, express: 2 },
    },
    paymentMethods: ["cod", "card", "upi", "netbanking", "wallet"],
    isDefault: true,
  },
  {
    code: "US",
    name: "United States",
    nativeName: "United States",
    flag: "🇺🇸",
    dialCode: "+1",
    currency: { code: "USD", symbol: "$", name: "US Dollar" },
    exchangeRate: 0.012,
    domain: "amazon.com",
    language: "en",
    timezone: "America/New_York",
    tax: { type: "Sales Tax", rate: 7.5, label: "Tax", includedInPrice: false },
    shipping: {
      freeShippingThreshold: 25,
      standardCost: 5.99,
      expressCost: 12.99,
      estimatedDays: { standard: 7, express: 3 },
    },
    paymentMethods: ["card", "paypal", "applepay", "googlepay"],
  },
  {
    code: "GB",
    name: "United Kingdom",
    nativeName: "United Kingdom",
    flag: "🇬🇧",
    dialCode: "+44",
    currency: { code: "GBP", symbol: "£", name: "British Pound" },
    exchangeRate: 0.0094,
    domain: "amazon.co.uk",
    language: "en",
    timezone: "Europe/London",
    tax: { type: "VAT", rate: 20, label: "VAT", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 20,
      standardCost: 3.99,
      expressCost: 7.99,
      estimatedDays: { standard: 5, express: 2 },
    },
    paymentMethods: ["card", "paypal", "applepay"],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    nativeName: "الإمارات",
    flag: "🇦🇪",
    dialCode: "+971",
    currency: { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
    exchangeRate: 0.044,
    domain: "amazon.ae",
    language: "ar",
    timezone: "Asia/Dubai",
    tax: { type: "VAT", rate: 5, label: "VAT", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 100,
      standardCost: 15,
      expressCost: 25,
      estimatedDays: { standard: 4, express: 1 },
    },
    paymentMethods: ["cod", "card", "applepay"],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    nativeName: "السعودية",
    flag: "🇸🇦",
    dialCode: "+966",
    currency: { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
    exchangeRate: 0.045,
    domain: "amazon.sa",
    language: "ar",
    timezone: "Asia/Riyadh",
    tax: { type: "VAT", rate: 15, label: "VAT", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 200,
      standardCost: 20,
      expressCost: 35,
      estimatedDays: { standard: 5, express: 2 },
    },
    paymentMethods: ["cod", "card"],
  },
  {
    code: "CA",
    name: "Canada",
    nativeName: "Canada",
    flag: "🇨🇦",
    dialCode: "+1",
    currency: { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
    exchangeRate: 0.016,
    domain: "amazon.ca",
    language: "en",
    timezone: "America/Toronto",
    tax: { type: "GST", rate: 13, label: "HST/GST", includedInPrice: false },
    shipping: {
      freeShippingThreshold: 35,
      standardCost: 7.99,
      expressCost: 14.99,
      estimatedDays: { standard: 7, express: 3 },
    },
    paymentMethods: ["card", "paypal"],
  },
  {
    code: "AU",
    name: "Australia",
    nativeName: "Australia",
    flag: "🇦🇺",
    dialCode: "+61",
    currency: { code: "AUD", symbol: "A$", name: "Australian Dollar" },
    exchangeRate: 0.018,
    domain: "amazon.com.au",
    language: "en",
    timezone: "Australia/Sydney",
    tax: { type: "GST", rate: 10, label: "GST", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 49,
      standardCost: 6.99,
      expressCost: 12.99,
      estimatedDays: { standard: 6, express: 2 },
    },
    paymentMethods: ["card", "paypal"],
  },
  {
    code: "SG",
    name: "Singapore",
    nativeName: "Singapore",
    flag: "🇸🇬",
    dialCode: "+65",
    currency: { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
    exchangeRate: 0.016,
    domain: "amazon.sg",
    language: "en",
    timezone: "Asia/Singapore",
    tax: { type: "GST", rate: 9, label: "GST", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 40,
      standardCost: 5,
      expressCost: 10,
      estimatedDays: { standard: 3, express: 1 },
    },
    paymentMethods: ["card", "paypal", "applepay"],
  },
  {
    code: "DE",
    name: "Germany",
    nativeName: "Deutschland",
    flag: "🇩🇪",
    dialCode: "+49",
    currency: { code: "EUR", symbol: "€", name: "Euro" },
    exchangeRate: 0.011,
    domain: "amazon.de",
    language: "de",
    timezone: "Europe/Berlin",
    tax: { type: "VAT", rate: 19, label: "MwSt", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 29,
      standardCost: 3.99,
      expressCost: 6.99,
      estimatedDays: { standard: 4, express: 2 },
    },
    paymentMethods: ["card", "paypal"],
  },
  {
    code: "FR",
    name: "France",
    nativeName: "France",
    flag: "🇫🇷",
    dialCode: "+33",
    currency: { code: "EUR", symbol: "€", name: "Euro" },
    exchangeRate: 0.011,
    domain: "amazon.fr",
    language: "fr",
    timezone: "Europe/Paris",
    tax: { type: "VAT", rate: 20, label: "TVA", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 25,
      standardCost: 4.99,
      expressCost: 8.99,
      estimatedDays: { standard: 4, express: 2 },
    },
    paymentMethods: ["card", "paypal"],
  },
  {
    code: "JP",
    name: "Japan",
    nativeName: "日本",
    flag: "🇯🇵",
    dialCode: "+81",
    currency: { code: "JPY", symbol: "¥", name: "Japanese Yen" },
    exchangeRate: 1.8,
    domain: "amazon.co.jp",
    language: "ja",
    timezone: "Asia/Tokyo",
    tax: { type: "VAT", rate: 10, label: "消費税", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 2000,
      standardCost: 350,
      expressCost: 700,
      estimatedDays: { standard: 3, express: 1 },
    },
    paymentMethods: ["card", "cod"],
  },
  {
    code: "CN",
    name: "China",
    nativeName: "中国",
    flag: "🇨🇳",
    dialCode: "+86",
    currency: { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
    exchangeRate: 0.087,
    domain: "amazon.cn",
    language: "zh",
    timezone: "Asia/Shanghai",
    tax: { type: "VAT", rate: 13, label: "VAT", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 99,
      standardCost: 10,
      expressCost: 25,
      estimatedDays: { standard: 5, express: 2 },
    },
    paymentMethods: ["card", "wallet"],
  },
  {
    code: "BR",
    name: "Brazil",
    nativeName: "Brasil",
    flag: "🇧🇷",
    dialCode: "+55",
    currency: { code: "BRL", symbol: "R$", name: "Brazilian Real" },
    exchangeRate: 0.061,
    domain: "amazon.com.br",
    language: "pt",
    timezone: "America/Sao_Paulo",
    tax: { type: "Sales Tax", rate: 17, label: "ICMS", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 79,
      standardCost: 9.99,
      expressCost: 19.99,
      estimatedDays: { standard: 8, express: 4 },
    },
    paymentMethods: ["card", "cod"],
  },
  {
    code: "ZA",
    name: "South Africa",
    nativeName: "South Africa",
    flag: "🇿🇦",
    dialCode: "+27",
    currency: { code: "ZAR", symbol: "R", name: "South African Rand" },
    exchangeRate: 0.22,
    domain: "amazon.co.za",
    language: "en",
    timezone: "Africa/Johannesburg",
    tax: { type: "VAT", rate: 15, label: "VAT", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 500,
      standardCost: 60,
      expressCost: 120,
      estimatedDays: { standard: 7, express: 3 },
    },
    paymentMethods: ["card", "cod"],
  },
  {
    code: "NG",
    name: "Nigeria",
    nativeName: "Nigeria",
    flag: "🇳🇬",
    dialCode: "+234",
    currency: { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
    exchangeRate: 19.5,
    domain: "amazon.ng",
    language: "en",
    timezone: "Africa/Lagos",
    tax: { type: "VAT", rate: 7.5, label: "VAT", includedInPrice: false },
    shipping: {
      freeShippingThreshold: 10000,
      standardCost: 1500,
      expressCost: 3000,
      estimatedDays: { standard: 7, express: 3 },
    },
    paymentMethods: ["card", "cod"],
  },
  {
    code: "PK",
    name: "Pakistan",
    nativeName: "پاکستان",
    flag: "🇵🇰",
    dialCode: "+92",
    currency: { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
    exchangeRate: 3.35,
    domain: "amazon.pk",
    language: "ur",
    timezone: "Asia/Karachi",
    tax: { type: "Sales Tax", rate: 17, label: "GST", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 2500,
      standardCost: 200,
      expressCost: 500,
      estimatedDays: { standard: 5, express: 2 },
    },
    paymentMethods: ["cod", "card"],
  },
  {
    code: "BD",
    name: "Bangladesh",
    nativeName: "বাংলাদেশ",
    flag: "🇧🇩",
    dialCode: "+880",
    currency: { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
    exchangeRate: 1.31,
    domain: "amazon.com.bd",
    language: "bn",
    timezone: "Asia/Dhaka",
    tax: { type: "VAT", rate: 15, label: "VAT", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 1000,
      standardCost: 80,
      expressCost: 200,
      estimatedDays: { standard: 5, express: 2 },
    },
    paymentMethods: ["cod", "card"],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    nativeName: "ශ්‍රී ලංකා",
    flag: "🇱🇰",
    dialCode: "+94",
    currency: { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
    exchangeRate: 3.6,
    domain: "amazon.lk",
    language: "en",
    timezone: "Asia/Colombo",
    tax: { type: "VAT", rate: 18, label: "VAT", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 3000,
      standardCost: 250,
      expressCost: 500,
      estimatedDays: { standard: 5, express: 2 },
    },
    paymentMethods: ["cod", "card"],
  },
  {
    code: "NP",
    name: "Nepal",
    nativeName: "नेपाल",
    flag: "🇳🇵",
    dialCode: "+977",
    currency: { code: "NPR", symbol: "₨", name: "Nepalese Rupee" },
    exchangeRate: 1.6,
    domain: "amazon.np",
    language: "ne",
    timezone: "Asia/Kathmandu",
    tax: { type: "VAT", rate: 13, label: "VAT", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 1500,
      standardCost: 100,
      expressCost: 250,
      estimatedDays: { standard: 6, express: 3 },
    },
    paymentMethods: ["cod", "card"],
  },
  {
    code: "MY",
    name: "Malaysia",
    nativeName: "Malaysia",
    flag: "🇲🇾",
    dialCode: "+60",
    currency: { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
    exchangeRate: 0.057,
    domain: "amazon.my",
    language: "ms",
    timezone: "Asia/Kuala_Lumpur",
    tax: { type: "Sales Tax", rate: 6, label: "SST", includedInPrice: true },
    shipping: {
      freeShippingThreshold: 80,
      standardCost: 8,
      expressCost: 18,
      estimatedDays: { standard: 4, express: 2 },
    },
    paymentMethods: ["card", "cod"],
  },
];

const seedCountries = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URL);
    console.log("✅ Connected to MongoDB");

    await Country.deleteMany({});
    console.log("🗑️  Cleared existing countries");

    await Country.insertMany(countries);
    console.log(`✅ Seeded ${countries.length} countries`);

    process.exit(0);
  } catch (err) {
    console.error("❌ Seed error:", err);
    process.exit(1);
  }
};

seedCountries();